version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: medsystem-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./gestao-clinica
    container_name: medsystem-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

